### ISSUE TITLE
'Clear' button in prof preferences form should re-enable disabled form fields

### ISSUE THREAD

**Issue by jjcarrcannings** [SENG-499-Company2-B01/Frontend#41]
When using the prof preferences form, if 'No' is selected for Able to teach (and all below form items are disabled as a result), clicking the 'Clear' button does not currently enable all the disabled fields, leaving the form in a invalid state with 'Yes' selected in Able to teach, but disabled fields below.
<img width="435" alt="image" src="https://github.com/SENG-499-Company2-B01/Frontend/assets/50784939/0475dc09-b146-45eb-86dc-1837aa1ab809">

**Comment by Erik-McKelvey** [comment]
Completed in #44
